[package]
name = "maid"
version = "0.1.0"
authors = ["Realvonmakeheat <dev@shrowd.org>"]
edition = "2021"
description = "CLI tool for cleaning up and restructuring AI-generated files"
license = "GPL-3.0"
keywords = ["cli", "cleanup", "ai", "files", "organization"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
regex = "1.10.2"
walkdir = "2.4.0"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slug = "0.1.4"
chrono = "0.4.31"
colored = "2.0.4"
indicatif = "0.17.7"
